name: Gradle CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '17', '18' ]
    name: Build with Java ${{ matrix.Java }}
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Setup Java ${{ matrix.Java }}
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: ${{ matrix.java }}
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Execute Gradle build
        run: ./gradlew build
      - name: Create distribution package
        run: ./gradlew jpackage
